SWAN GPU
cernbox/uboxed pull request #3
Opened 2019-07-11 14:06 UTC by omazapa

Hi Guys,

this is the code to install the nvidia-docker2 middleware 
and to check if the nvidia is loaded.
The driver should be installed in the host by the user.

Cheers
Omar.

2019-07-11 14:54 UTC, ebocchi requested changes

2019-07-11 14:54 UTC, ebocchi commented on SetupInstall-Centos7.sh
> +  sudo tee /etc/yum.repos.d/nvidia-docker.repo
Do we really need to add the repo file?
Cannot we just install the package without messing around with the local manager config?

2019-07-11 14:54 UTC, ebocchi commented on SetupInstall-Centos7.sh
> +    echo "Exiting..."
If I say no, I can still use the whole machinery without GPUs.
There is no need to bail out. And, in fact, you are not bailing out...
Please, echo something like "Continuing without GPU support"

2019-07-11 14:54 UTC, ebocchi commented on SetupInstall-Ubuntu.sh
> +  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
Same comment as for CC7. Cannot we simply install the package?

2019-07-11 14:55 UTC, ebocchi commented
Thanks a lot, @omazapa !
I have a couple of minor comments on the code.
Is there any upstream-provided list of the compatible hardware?
It would be good to tell people to check if their machine is supported before hand.

Cheers!

2019-07-19 11:11 UTC, omazapa commented
Please don't do the review yet,
I am testing it in a clean installation of Centos7 and ubuntu.
I will be uploading the changes.

2019-07-19 14:35 UTC, omazapa commented
Hi @ebocchi 
I did the changes and It was  tested it in Centos 7 and Ubuntu 16.04/18.04 
You can do the review again.

Thank you for the review!

2019-07-22 07:39 UTC, omazapa commented
Hi @ebocchi 
About the hardware https://docs.nvidia.com/deploy/cuda-compatibility/index.html#support-hardware
I can see that all architectures are supported except the video card with Fermi.

Cheers.
Omar.


> Thanks a lot, @omazapa !
> I have a couple of minor comments on the code.
> Is there any upstream-provided list of the compatible hardware?
> It would be good to tell people to check if their machine is supported beforehand.
> 
> Cheers!

About the hardware, appear to be compatible with any card compatible with cuda 10

2019-07-31 08:31 UTC, ebocchi commented on SetupInstall-Centos7.sh
> +  sudo tee /etc/yum.repos.d/nvidia-docker.repo
Fixed.

2019-07-31 08:32 UTC, ebocchi commented on SetupInstall-Ubuntu.sh
> +  sudo tee /etc/apt/sources.list.d/nvidia-docker.list
Fixed.

2019-07-31 08:34 UTC, merged